### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by ItsCEED** [DeltaEvo/proxy-scraper#5]
```
(function (exports, require, module, __filename, __dirname) { import scrapers from './src/scrapers'
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```
What could be the issue

**Comment by DeltaEvo** [comment]
Could you give me the code that are you using please ?

**Comment by ItsCEED** [comment]
@DeltaEvo i manage to solve the issue with babel-node insted running it with node.

Its the original code that is here on github only modded to store the proxies in database and some sources removed since they were returning so many dead proxies
